In [55]:
import xlrd
import pandas as pd
codigos = ['Codigos']
book = xlrd.open_workbook("indices.xlsx")
print("Número de abas: ", book.nsheets)
print("Nomes das Planilhas:", book.sheet_names())
df = pd.DataFrame(columns=['Código','Ação','Tipo','Qtde. Teórica','Part.'])
for i in range(book.nsheets):
    sh = book.sheet_by_index(i)
    print(sh.name, sh.nrows, sh.ncols)
    for cx in range(sh.ncols-4):   
        print(sh.col(cx)[1:-2])   
        codigos.append(sh.col(cx)[1:-2])

Número de abas:  11
Nomes das Planilhas: ['ICON', 'IDIV', 'IEE', 'IFNC', 'IMAT', 'IMOB', 'INDX', 'IVBX 2', 'MLCX', 'SMLL', 'UTIL']
ICON 57 5
[text:'ABEV3', text:'ALPA4', text:'AMAR3', text:'ANIM3', text:'ARZZ3', text:'BEEF3', text:'BKBR3', text:'BRFS3', text:'BTOW3', text:'CAML3', text:'CRFB3', text:'CVCB3', text:'CYRE3', text:'DIRR3', text:'ESTC3', text:'EVEN3', text:'EZTC3', text:'FLRY3', text:'GFSA3', text:'GNDI3', text:'GRND3', text:'GUAR3', text:'HAPV3', text:'HBOR3', text:'HGTX3', text:'HYPE3', text:'JBSS3', text:'KROT3', text:'LAME3', text:'LAME4', text:'LEVE3', text:'LREN3', text:'MDIA3', text:'MEAL3', text:'MGLU3', text:'MOVI3', text:'MPLU3', text:'MRFG3', text:'MRVE3', text:'MYPK3', text:'NATU3', text:'ODPV3', text:'PARD3', text:'PCAR4', text:'QUAL3', text:'RADL3', text:'RENT3', text:'SEER3', text:'SLCE3', text:'SMLS3', text:'SMTO3', text:'TEND3', text:'VULC3', text:'VVAR11']
IDIV 36 5
[text:'ABCB4', text:'BBDC4', text:'BBSE3', text:'BRAP4', text:'BRKM5', text:'BRSR6', text:'CCRO3', text:'CGAS5', text:'CMIG4', text:'CPLE6', text:'CSAN3', text:'EGIE3', text:'ENBR3', text:'EZTC3', text:'FESA4', text:'GRND3', text:'HGTX3', text:'ITSA4', text:'ITUB3', text:'ITUB4', text:'LEVE3', text:'MPLU3', text:'MRVE3', text:'PSSA3', text:'QUAL3', text:'SANB11', text:'SAPR11', text:'TAEE11', text:'TIET11', text:'TRPL4', text:'TUPY3', text:'UNIP6', text:'VIVT4']
IEE 23 5
[text:'ALUP11', text:'CESP6', text:'CMIG4', text:'COCE5', text:'CPFE3', text:'CPLE6', text:'CPRE3', text:'EGIE3', text:'ELET3', text:'ELPL3', text:'ENBR3', text:'ENEV3', text:'ENGI11', text:'EQTL3', text:'LIGT3', text:'OMGE3', text:'RNEW11', text:'TAEE11', text:'TIET11', text:'TRPL4']
IFNC 19 5
[text:'ABCB4', text:'B3SA3', text:'BBAS3', text:'BBDC3', text:'BBDC4', text:'BBSE3', text:'BPAC11', text:'BRSR6', text:'CIEL3', text:'IRBR3', text:'ITSA4', text:'ITUB3', text:'ITUB4', text:'PSSA3', text:'SANB11', text:'SULA11']
IMAT 16 5
[text:'BRAP4', text:'BRKM5', text:'CSNA3', text:'DTEX3', text:'FESA4', text:'FIBR3', text:'GGBR4', text:'GOAU4', text:'KLBN11', text:'SUZB3', text:'UNIP6', text:'USIM5', text:'VALE3']
IMOB 16 5
[text:'ALSC3', text:'BRML3', text:'BRPR3', text:'CYRE3', text:'DIRR3', text:'EVEN3', text:'EZTC3', text:'GFSA3', text:'HBOR3', text:'IGTA3', text:'MRVE3', text:'MULT3', text:'TEND3']
INDX 47 5
[text:'ABEV3', text:'ALPA4', text:'BEEF3', text:'BRFS3', text:'BRKM5', text:'CAML3', text:'CSNA3', text:'CYRE3', text:'DIRR3', text:'DTEX3', text:'EMBR3', text:'EVEN3', text:'EZTC3', text:'FESA4', text:'FIBR3', text:'GFSA3', text:'GGBR4', text:'GOAU4', text:'GRND3', text:'HBOR3', text:'HGTX3', text:'JBSS3', text:'JHSF3', text:'KLBN11', text:'LEVE3', text:'MAGG3', text:'MDIA3', text:'MRFG3', text:'MRVE3', text:'MYPK3', text:'NATU3', text:'PMAM3', text:'POMO4', text:'PTBL3', text:'RAPT4', text:'SMTO3', text:'SUZB3', text:'TCSA3', text:'TEND3', text:'TUPY3', text:'UNIP6', text:'USIM5', text:'VULC3', text:'WEGE3']
IVBX 2 53 5
[text:'BBSE3', text:'BRAP4', text:'BRDT3', text:'BRFS3', text:'BRKM5', text:'BRML3', text:'BTOW3', text:'CCRO3', text:'CIEL3', text:'CMIG4', text:'CRFB3', text:'CSAN3', text:'CSNA3', text:'CVCB3', text:'CYRE3', text:'ECOR3', text:'EGIE3', text:'ELET3', text:'EMBR3', text:'ENBR3', text:'EQTL3', text:'ESTC3', text:'FIBR3', text:'FLRY3', text:'GGBR4', text:'GOAU4', text:'GOLL4', text:'HYPE3', text:'IGTA3', text:'JBSS3', text:'KLBN11', text:'KROT3', text:'LAME4', text:'LREN3', text:'MGLU3', text:'MRVE3', text:'MULT3', text:'NATU3', text:'PCAR4', text:'QUAL3', text:'RADL3', text:'RAIL3', text:'RENT3', text:'SBSP3', text:'SMLS3', text:'TAEE11', text:'TIMP3', text:'UGPA3', text:'VVAR11', text:'WEGE3']
MLCX 64 5
[text:'ABEV3', text:'B3SA3', text:'BBAS3', text:'BBDC3', text:'BBDC4', text:'BBSE3', text:'BPAC11', text:'BRDT3', text:'BRFS3', text:'BRKM5', text:'BTOW3', text:'CCRO3', text:'CIEL3', text:'CMIG3', text:'CMIG4', text:'CPFE3', text:'CRFB3', text:'CSAN3', text:'CSNA3', text:'EGIE3', text:'ELET3', text:'ELET6', text:'EMBR3', text:'ENGI11', text:'EQTL3', text:'FIBR3', text:'GGBR4', text:'GNDI3', text:'HAPV3', text:'HYPE3', text:'IRBR3', text:'ITSA4', text:'ITUB3', text:'ITUB4', text:'JBSS3', text:'KLBN11', text:'KROT3', text:'LAME3', text:'LAME4', text:'LREN3', text:'MDIA3', text:'MGLU3', text:'MULT3', text:'NATU3', text:'PCAR4', text:'PETR3', text:'PETR4', text:'PSSA3', text:'RADL3', text:'RAIL3', text:'RENT3', text:'SANB11', text:'SBSP3', text:'SUZB3', text:'TIMP3', text:'TRPL4', text:'UGPA3', text:'USIM5', text:'VALE3', text:'VIVT4', text:'WEGE3']
SMLL 80 5
[text:'ABCB4', text:'ALPA4', text:'ALSC3', text:'ALUP11', text:'AMAR3', text:'ANIM3', text:'ARZZ3', text:'AZUL4', text:'BEEF3', text:'BKBR3', text:'BRAP4', text:'BRML3', text:'BRPR3', text:'BRSR6', text:'CAML3', text:'CESP6', text:'CPLE6', text:'CSMG3', text:'CVCB3', text:'CYRE3', text:'DIRR3', text:'DMMO3', text:'DTEX3', text:'ECOR3', text:'ENBR3', text:'ENEV3', text:'ESTC3', text:'EVEN3', text:'EZTC3', text:'FESA4', text:'FLRY3', text:'GFSA3', text:'GOAU4', text:'GOLL4', text:'GRND3', text:'GUAR3', text:'HBOR3', text:'HGTX3', text:'IGTA3', text:'LEVE3', text:'LIGT3', text:'LINX3', text:'MEAL3', text:'MOVI3', text:'MPLU3', text:'MRFG3', text:'MRVE3', text:'MYPK3', text:'ODPV3', text:'OMGE3', text:'PARD3', text:'POMO4', text:'PRIO3', text:'PTBL3', text:'QGEP3', text:'QUAL3', text:'RAPT4', text:'RLOG3', text:'SAPR11', text:'SEER3', text:'SLCE3', text:'SMLS3', text:'SMTO3', text:'STBP3', text:'SULA11', text:'TAEE11', text:'TCSA3', text:'TEND3', text:'TGMA3', text:'TIET11', text:'TOTS3', text:'TUPY3', text:'UNIP6', text:'VLID3', text:'VULC3', text:'VVAR11', text:'WIZS3']
UTIL 25 5
[text:'ALUP11', text:'CESP6', text:'CGAS5', text:'CMIG3', text:'CMIG4', text:'CPFE3', text:'CPLE6', text:'CSMG3', text:'EGIE3', text:'ELET3', text:'ELET6', text:'ENBR3', text:'ENEV3', text:'ENGI11', text:'EQTL3', text:'LIGT3', text:'OMGE3', text:'SAPR11', text:'SBSP3', text:'TAEE11', text:'TIET11', text:'TRPL4']

In [58]:
df=pd.DataFrame(codigos)
df

                                                    0
0                                             Codigos
1   [text:'ABEV3', text:'ALPA4', text:'AMAR3', tex...
2   [text:'ABCB4', text:'BBDC4', text:'BBSE3', tex...
3   [text:'ALUP11', text:'CESP6', text:'CMIG4', te...
4   [text:'ABCB4', text:'B3SA3', text:'BBAS3', tex...
5   [text:'BRAP4', text:'BRKM5', text:'CSNA3', tex...
6   [text:'ALSC3', text:'BRML3', text:'BRPR3', tex...
7   [text:'ABEV3', text:'ALPA4', text:'BEEF3', tex...
8   [text:'BBSE3', text:'BRAP4', text:'BRDT3', tex...
9   [text:'ABEV3', text:'B3SA3', text:'BBAS3', tex...
10  [text:'ABCB4', text:'ALPA4', text:'ALSC3', tex...
11  [text:'ALUP11', text:'CESP6', text:'CGAS5', te...

In [75]:
import xlrd
import pandas as pd
codigos = ['Codigos']
book = xlrd.open_workbook("indices.xlsx")
for i in range(book.nsheets):
    dataframe_excel = pd.read_excel("indices.xlsx",sheet_name=i, header=0)
    dataframe_excel.append(dataframe_excel[:-2])

In [76]:
dataframe_excel

                     Código           Ação    Tipo  Qtde. Teórica  Part. (%)
0                     ALUP11        ALUPAR  UNT N2   1.509606e+08      2.427
1                      CESP6          CESP  PNB N1   1.820177e+08      2.611
2                      CGAS5        COMGAS     PNA   2.349662e+07      1.280
3                      CMIG3         CEMIG   ON N1   2.389718e+08      2.257
4                      CMIG4         CEMIG   PN N1   9.697192e+08      9.794
5                      CPFE3  CPFL ENERGIA   ON NM   5.339266e+07      1.328
6                      CPLE6         COPEL  PNB N1   1.010137e+08      2.597
7                      CSMG3        COPASA   ON NM   6.153261e+07      3.126
8                      EGIE3  ENGIE BRASIL   ON NM   2.038542e+08      7.385
9                      ELET3    ELETROBRAS   ON N1   2.696678e+08      5.880
10                     ELET6    ELETROBRAS  PNB N1   2.259648e+08      5.991
11                     ENBR3   ENERGIAS BR   ON NM   2.953430e+08      4.072
12                     ENEV3         ENEVA   ON NM   3.149905e+08      4.205
13                    ENGI11      ENERGISA  UNT N2   2.422160e+08      7.673
14                     EQTL3    EQUATORIAL   ON NM   1.981635e+08     11.816
15                     LIGT3     LIGHT S/A   ON NM   9.762948e+07      1.541
16                     OMGE3     OMEGA GER   ON NM   4.494403e+07      0.697
17                    SAPR11       SANEPAR  UNT N2   6.699718e+07      3.078
18                     SBSP3        SABESP   ON NM   3.053851e+08      8.512
19                    TAEE11         TAESA  UNT N2   2.185683e+08      4.679
20                    TIET11   AES TIETE E  UNT N2   2.978854e+08      2.970
21                     TRPL4  TRAN PAULIST   PN N1   9.895026e+07      6.081
22  Quantidade Teórica Total           NaN     NaN   4.661664e+09    100.000
23                   Redutor           NaN     NaN   2.203717e+07        NaN