In [55]:
import xlrd
import pandas as pd
codigos = ['Codigos']
book = xlrd.open_workbook("indices.xlsx")
print("Número de abas: ", book.nsheets)
print("Nomes das Planilhas:", book.sheet_names())
df = pd.DataFrame(columns=['Código','Ação','Tipo','Qtde. Teórica','Part.'])
for i in range(book.nsheets):
    sh = book.sheet_by_index(i)
    print(sh.name, sh.nrows, sh.ncols)
    for cx in range(sh.ncols-4):   
        print(sh.col(cx)[1:-2])   
        codigos.append(sh.col(cx)[1:-2])

Número de abas:  11
Nomes das Planilhas: ['ICON', 'IDIV', 'IEE', 'IFNC', 'IMAT', 'IMOB', 'INDX', 'IVBX 2', 'MLCX', 'SMLL', 'UTIL']
ICON 57 5
[text:'ABEV3', text:'ALPA4', text:'AMAR3', text:'ANIM3', text:'ARZZ3', text:'BEEF3', text:'BKBR3', text:'BRFS3', text:'BTOW3', text:'CAML3', text:'CRFB3', text:'CVCB3', text:'CYRE3', text:'DIRR3', text:'ESTC3', text:'EVEN3', text:'EZTC3', text:'FLRY3', text:'GFSA3', text:'GNDI3', text:'GRND3', text:'GUAR3', text:'HAPV3', text:'HBOR3', text:'HGTX3', text:'HYPE3', text:'JBSS3', text:'KROT3', text:'LAME3', text:'LAME4', text:'LEVE3', text:'LREN3', text:'MDIA3', text:'MEAL3', text:'MGLU3', text:'MOVI3', text:'MPLU3', text:'MRFG3', text:'MRVE3', text:'MYPK3', text:'NATU3', text:'ODPV3', text:'PARD3', text:'PCAR4', text:'QUAL3', text:'RADL3', text:'RENT3', text:'SEER3', text:'SLCE3', text:'SMLS3', text:'SMTO3', text:'TEND3', text:'VULC3', text:'VVAR11']
IDIV 36 5
[text:'ABCB4', text:'BBDC4', text:'BBSE3', text:'BRAP4', text:'BRKM5', text:'BRSR6', text:'CCRO3', text:'CGAS5', text:'CMIG4', text:'CPLE6', text:'CSAN3', text:'EGIE3', text:'ENBR3', text:'EZTC3', text:'FESA4', text:'GRND3', text:'HGTX3', text:'ITSA4', text:'ITUB3', text:'ITUB4', text:'LEVE3', text:'MPLU3', text:'MRVE3', text:'PSSA3', text:'QUAL3', text:'SANB11', text:'SAPR11', text:'TAEE11', text:'TIET11', text:'TRPL4', text:'TUPY3', text:'UNIP6', text:'VIVT4']
IEE 23 5
[text:'ALUP11', text:'CESP6', text:'CMIG4', text:'COCE5', text:'CPFE3', text:'CPLE6', text:'CPRE3', text:'EGIE3', text:'ELET3', text:'ELPL3', text:'ENBR3', text:'ENEV3', text:'ENGI11', text:'EQTL3', text:'LIGT3', text:'OMGE3', text:'RNEW11', text:'TAEE11', text:'TIET11', text:'TRPL4']
IFNC 19 5
[text:'ABCB4', text:'B3SA3', text:'BBAS3', text:'BBDC3', text:'BBDC4', text:'BBSE3', text:'BPAC11', text:'BRSR6', text:'CIEL3', text:'IRBR3', text:'ITSA4', text:'ITUB3', text:'ITUB4', text:'PSSA3', text:'SANB11', text:'SULA11']
IMAT 16 5
[text:'BRAP4', text:'BRKM5', text:'CSNA3', text:'DTEX3', text:'FESA4', text:'FIBR3', text:'GGBR4', text:'GOAU4', text:'KLBN11', text:'SUZB3', text:'UNIP6', text:'USIM5', text:'VALE3']
IMOB 16 5
[text:'ALSC3', text:'BRML3', text:'BRPR3', text:'CYRE3', text:'DIRR3', text:'EVEN3', text:'EZTC3', text:'GFSA3', text:'HBOR3', text:'IGTA3', text:'MRVE3', text:'MULT3', text:'TEND3']
INDX 47 5
[text:'ABEV3', text:'ALPA4', text:'BEEF3', text:'BRFS3', text:'BRKM5', text:'CAML3', text:'CSNA3', text:'CYRE3', text:'DIRR3', text:'DTEX3', text:'EMBR3', text:'EVEN3', text:'EZTC3', text:'FESA4', text:'FIBR3', text:'GFSA3', text:'GGBR4', text:'GOAU4', text:'GRND3', text:'HBOR3', text:'HGTX3', text:'JBSS3', text:'JHSF3', text:'KLBN11', text:'LEVE3', text:'MAGG3', text:'MDIA3', text:'MRFG3', text:'MRVE3', text:'MYPK3', text:'NATU3', text:'PMAM3', text:'POMO4', text:'PTBL3', text:'RAPT4', text:'SMTO3', text:'SUZB3', text:'TCSA3', text:'TEND3', text:'TUPY3', text:'UNIP6', text:'USIM5', text:'VULC3', text:'WEGE3']
IVBX 2 53 5
[text:'BBSE3', text:'BRAP4', text:'BRDT3', text:'BRFS3', text:'BRKM5', text:'BRML3', text:'BTOW3', text:'CCRO3', text:'CIEL3', text:'CMIG4', text:'CRFB3', text:'CSAN3', text:'CSNA3', text:'CVCB3', text:'CYRE3', text:'ECOR3', text:'EGIE3', text:'ELET3', text:'EMBR3', text:'ENBR3', text:'EQTL3', text:'ESTC3', text:'FIBR3', text:'FLRY3', text:'GGBR4', text:'GOAU4', text:'GOLL4', text:'HYPE3', text:'IGTA3', text:'JBSS3', text:'KLBN11', text:'KROT3', text:'LAME4', text:'LREN3', text:'MGLU3', text:'MRVE3', text:'MULT3', text:'NATU3', text:'PCAR4', text:'QUAL3', text:'RADL3', text:'RAIL3', text:'RENT3', text:'SBSP3', text:'SMLS3', text:'TAEE11', text:'TIMP3', text:'UGPA3', text:'VVAR11', text:'WEGE3']
MLCX 64 5
[text:'ABEV3', text:'B3SA3', text:'BBAS3', text:'BBDC3', text:'BBDC4', text:'BBSE3', text:'BPAC11', text:'BRDT3', text:'BRFS3', text:'BRKM5', text:'BTOW3', text:'CCRO3', text:'CIEL3', text:'CMIG3', text:'CMIG4', text:'CPFE3', text:'CRFB3', text:'CSAN3', text:'CSNA3', text:'EGIE3', text:'ELET3', text:'ELET6', text:'EMBR3', text:'ENGI11', text:'EQTL3', text:'FIBR3', text:'GGBR4', text:'GNDI3', text:'HAPV3', text:'HYPE3', text:'IRBR3', text:'ITSA4', text:'ITUB3', text:'ITUB4', text:'JBSS3', text:'KLBN11', text:'KROT3', text:'LAME3', text:'LAME4', text:'LREN3', text:'MDIA3', text:'MGLU3', text:'MULT3', text:'NATU3', text:'PCAR4', text:'PETR3', text:'PETR4', text:'PSSA3', text:'RADL3', text:'RAIL3', text:'RENT3', text:'SANB11', text:'SBSP3', text:'SUZB3', text:'TIMP3', text:'TRPL4', text:'UGPA3', text:'USIM5', text:'VALE3', text:'VIVT4', text:'WEGE3']
SMLL 80 5
[text:'ABCB4', text:'ALPA4', text:'ALSC3', text:'ALUP11', text:'AMAR3', text:'ANIM3', text:'ARZZ3', text:'AZUL4', text:'BEEF3', text:'BKBR3', text:'BRAP4', text:'BRML3', text:'BRPR3', text:'BRSR6', text:'CAML3', text:'CESP6', text:'CPLE6', text:'CSMG3', text:'CVCB3', text:'CYRE3', text:'DIRR3', text:'DMMO3', text:'DTEX3', text:'ECOR3', text:'ENBR3', text:'ENEV3', text:'ESTC3', text:'EVEN3', text:'EZTC3', text:'FESA4', text:'FLRY3', text:'GFSA3', text:'GOAU4', text:'GOLL4', text:'GRND3', text:'GUAR3', text:'HBOR3', text:'HGTX3', text:'IGTA3', text:'LEVE3', text:'LIGT3', text:'LINX3', text:'MEAL3', text:'MOVI3', text:'MPLU3', text:'MRFG3', text:'MRVE3', text:'MYPK3', text:'ODPV3', text:'OMGE3', text:'PARD3', text:'POMO4', text:'PRIO3', text:'PTBL3', text:'QGEP3', text:'QUAL3', text:'RAPT4', text:'RLOG3', text:'SAPR11', text:'SEER3', text:'SLCE3', text:'SMLS3', text:'SMTO3', text:'STBP3', text:'SULA11', text:'TAEE11', text:'TCSA3', text:'TEND3', text:'TGMA3', text:'TIET11', text:'TOTS3', text:'TUPY3', text:'UNIP6', text:'VLID3', text:'VULC3', text:'VVAR11', text:'WIZS3']
UTIL 25 5
[text:'ALUP11', text:'CESP6', text:'CGAS5', text:'CMIG3', text:'CMIG4', text:'CPFE3', text:'CPLE6', text:'CSMG3', text:'EGIE3', text:'ELET3', text:'ELET6', text:'ENBR3', text:'ENEV3', text:'ENGI11', text:'EQTL3', text:'LIGT3', text:'OMGE3', text:'SAPR11', text:'SBSP3', text:'TAEE11', text:'TIET11', text:'TRPL4']

In [58]:
df=pd.DataFrame(codigos)
df

                                                    0
0                                             Codigos
1   [text:'ABEV3', text:'ALPA4', text:'AMAR3', tex...
2   [text:'ABCB4', text:'BBDC4', text:'BBSE3', tex...
3   [text:'ALUP11', text:'CESP6', text:'CMIG4', te...
4   [text:'ABCB4', text:'B3SA3', text:'BBAS3', tex...
5   [text:'BRAP4', text:'BRKM5', text:'CSNA3', tex...
6   [text:'ALSC3', text:'BRML3', text:'BRPR3', tex...
7   [text:'ABEV3', text:'ALPA4', text:'BEEF3', tex...
8   [text:'BBSE3', text:'BRAP4', text:'BRDT3', tex...
9   [text:'ABEV3', text:'B3SA3', text:'BBAS3', tex...
10  [text:'ABCB4', text:'ALPA4', text:'ALSC3', tex...
11  [text:'ALUP11', text:'CESP6', text:'CGAS5', te...

In [23]:
import xlrd
import pandas as pd
codigos = ['Codigos']
frame = []
book = xlrd.open_workbook("indices.xlsx")
for i in range(book.nsheets):
    dataframe_excel = pd.read_excel("indices.xlsx",sheet_name=i, header=0)[:-2]
    dataframe_excel['Indices']=book.sheet_names()[i]
    frame.append(dataframe_excel[:-2])
teste=pd.concat(frame)  
teste.head()

  Código           Ação      Tipo  Qtde. Teórica  Part. (%) Indices
0   ABEV3     AMBEV S/A        ON   3.188072e+09     18.179    ICON
1   ALPA4    ALPARGATAS     PN N1   1.504626e+08      0.643    ICON
2   AMAR3  LOJAS MARISA     ON NM   5.307442e+07      0.070    ICON
3   ANIM3         ANIMA     ON NM   3.589651e+07      0.174    ICON
4   ARZZ3     AREZZO CO  ON ED NM   4.413731e+07      0.637    ICON

In [28]:
teste.columns = ['Codigo','Ação','Tipo','Qtd.','Part.','I_Name']

In [36]:
df_ICON = teste[teste['I_Name'] == 'ICON']
df_IDIV = teste[teste['I_Name'] == 'IDIV']
df_IEE = teste[teste['I_Name'] == 'IEE']
df_IFNC = teste[teste['I_Name'] == 'IFNC']
df_IMAT = teste[teste['I_Name'] == 'IAMT']
df_IMOB = teste[teste['I_Name'] == 'IMOB']
df_INDX = teste[teste['I_Name'] == 'INDX']
df_IVBX2 = teste[teste['I_Name'] == 'IVBX2']
df_MLCX =  teste[teste['I_Name'] == 'MLCX']
df_SMLL = teste[teste['I_Name'] == 'SMLL']
df_UTIL = teste[teste['I_Name'] == 'UTIL']

In [37]:
print(df_ICON['Codigo'])
print(df_IDIV['Codigo'])
print(df_IEE['Codigo'])
print(df_IFNC['Codigo']) 
print(df_IMAT['Codigo'])
print(df_IMOB['Codigo'])
print(df_INDX['Codigo'])
print(df_IVBX2['Codigo']) 
print(df_MLCX['Codigo'])
print(df_SMLL['Codigo']) 
print(df_UTIL['Codigo'])

0     ABEV3
1     ALPA4
2     AMAR3
3     ANIM3
4     ARZZ3
5     BEEF3
6     BKBR3
7     BRFS3
8     BTOW3
9     CAML3
10    CRFB3
11    CVCB3
12    CYRE3
13    DIRR3
14    ESTC3
15    EVEN3
16    EZTC3
17    FLRY3
18    GFSA3
19    GNDI3
20    GRND3
21    GUAR3
22    HAPV3
23    HBOR3
24    HGTX3
25    HYPE3
26    JBSS3
27    KROT3
28    LAME3
29    LAME4
30    LEVE3
31    LREN3
32    MDIA3
33    MEAL3
34    MGLU3
35    MOVI3
36    MPLU3
37    MRFG3
38    MRVE3
39    MYPK3
40    NATU3
41    ODPV3
42    PARD3
43    PCAR4
44    QUAL3
45    RADL3
46    RENT3
47    SEER3
48    SLCE3
49    SMLS3
50    SMTO3
51    TEND3
Name: Codigo, dtype: object
0      ABCB4
1      BBDC4
2      BBSE3
3      BRAP4
4      BRKM5
5      BRSR6
6      CCRO3
7      CGAS5
8      CMIG4
9      CPLE6
10     CSAN3
11     EGIE3
12     ENBR3
13     EZTC3
14     FESA4
15     GRND3
16     HGTX3
17     ITSA4
18     ITUB3
19     ITUB4
20     LEVE3
21     MPLU3
22     MRVE3
23     PSSA3
24     QUAL3
25    SANB11
26    SAPR11
27    TAEE11
28    TIET11
29     TRPL4
30     TUPY3
Name: Codigo, dtype: object
0     ALUP11
1      CESP6
2      CMIG4
3      COCE5
4      CPFE3
5      CPLE6
6      CPRE3
7      EGIE3
8      ELET3
9      ELPL3
10     ENBR3
11     ENEV3
12    ENGI11
13     EQTL3
14     LIGT3
15     OMGE3
16    RNEW11
17    TAEE11
Name: Codigo, dtype: object
0      ABCB4
1      B3SA3
2      BBAS3
3      BBDC3
4      BBDC4
5      BBSE3
6     BPAC11
7      BRSR6
8      CIEL3
9      IRBR3
10     ITSA4
11     ITUB3
12     ITUB4
13     PSSA3
Name: Codigo, dtype: object
Series([], Name: Codigo, dtype: object)
0     ALSC3
1     BRML3
2     BRPR3
3     CYRE3
4     DIRR3
5     EVEN3
6     EZTC3
7     GFSA3
8     HBOR3
9     IGTA3
10    MRVE3
Name: Codigo, dtype: object
0      ABEV3
1      ALPA4
2      BEEF3
3      BRFS3
4      BRKM5
5      CAML3
6      CSNA3
7      CYRE3
8      DIRR3
9      DTEX3
10     EMBR3
11     EVEN3
12     EZTC3
13     FESA4
14     FIBR3
15     GFSA3
16     GGBR4
17     GOAU4
18     GRND3
19     HBOR3
20     HGTX3
21     JBSS3
22     JHSF3
23    KLBN11
24     LEVE3
25     MAGG3
26     MDIA3
27     MRFG3
28     MRVE3
29     MYPK3
30     NATU3
31     PMAM3
32     POMO4
33     PTBL3
34     RAPT4
35     SMTO3
36     SUZB3
37     TCSA3
38     TEND3
39     TUPY3
40     UNIP6
41     USIM5
Name: Codigo, dtype: object
Series([], Name: Codigo, dtype: object)
0      ABEV3
1      B3SA3
2      BBAS3
3      BBDC3
4      BBDC4
5      BBSE3
6     BPAC11
7      BRDT3
8      BRFS3
9      BRKM5
10     BTOW3
11     CCRO3
12     CIEL3
13     CMIG3
14     CMIG4
15     CPFE3
16     CRFB3
17     CSAN3
18     CSNA3
19     EGIE3
20     ELET3
21     ELET6
22     EMBR3
23    ENGI11
24     EQTL3
25     FIBR3
26     GGBR4
27     GNDI3
28     HAPV3
29     HYPE3
30     IRBR3
31     ITSA4
32     ITUB3
33     ITUB4
34     JBSS3
35    KLBN11
36     KROT3
37     LAME3
38     LAME4
39     LREN3
40     MDIA3
41     MGLU3
42     MULT3
43     NATU3
44     PCAR4
45     PETR3
46     PETR4
47     PSSA3
48     RADL3
49     RAIL3
50     RENT3
51    SANB11
52     SBSP3
53     SUZB3
54     TIMP3
55     TRPL4
56     UGPA3
57     USIM5
58     VALE3
Name: Codigo, dtype: object
0      ABCB4
1      ALPA4
2      ALSC3
3     ALUP11
4      AMAR3
5      ANIM3
6      ARZZ3
7      AZUL4
8      BEEF3
9      BKBR3
10     BRAP4
11     BRML3
12     BRPR3
13     BRSR6
14     CAML3
15     CESP6
16     CPLE6
17     CSMG3
18     CVCB3
19     CYRE3
20     DIRR3
21     DMMO3
22     DTEX3
23     ECOR3
24     ENBR3
25     ENEV3
26     ESTC3
27     EVEN3
28     EZTC3
29     FESA4
       ...
45     MRFG3
46     MRVE3
47     MYPK3
48     ODPV3
49     OMGE3
50     PARD3
51     POMO4
52     PRIO3
53     PTBL3
54     QGEP3
55     QUAL3
56     RAPT4
57     RLOG3
58    SAPR11
59     SEER3
60     SLCE3
61     SMLS3
62     SMTO3
63     STBP3
64    SULA11
65    TAEE11
66     TCSA3
67     TEND3
68     TGMA3
69    TIET11
70     TOTS3
71     TUPY3
72     UNIP6
73     VLID3
74     VULC3
Name: Codigo, Length: 75, dtype: object
0     ALUP11
1      CESP6
2      CGAS5
3      CMIG3
4      CMIG4
5      CPFE3
6      CPLE6
7      CSMG3
8      EGIE3
9      ELET3
10     ELET6
11     ENBR3
12     ENEV3
13    ENGI11
14     EQTL3
15     LIGT3
16     OMGE3
17    SAPR11
18     SBSP3
19    TAEE11
Name: Codigo, dtype: object