In [2]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Set 21 09:11:31 2018

@author:Eduardo S. Sales
Universidade de Brasilia - UnB
"""
%matplotlib notebook 
import datetime
from pandas import *
import matplotlib.mlab as mlab
import scipy.signal as signal
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pandas_datareader.data as pdr
import fix_yahoo_finance as yf
import datetime as dt
import seaborn as sns
sns.set()

1) Considerando os índices da Bovespa, pertencente aos conjuntos Setorial ou por Segmento, (i) escolha aos seu critério 5 (cinco) índices e entre esses escolhidos os 5 (cinco) papeis mais líquidos.
http://www.bmfbovespa.com.br/pt_br/produtos/indices/

Os índices escolhidos são do conjunto Setorial, mais especificamente os que compõem a carteira do IMOB( Índice Imobiliário): http://www.bmfbovespa.com.br/pt_br/produtos/indices/indices-setoriais/indice-bm-fbovespa-imobiliario-imob-composicao-da-carteira.htm 

Para definir os 5 mais Líquidos, foi calculadada a média de volume diário de cada índice. Os que obtiveram maior volume diário médio, teoricamente possuem maior liquidez.

In [35]:
def yahoo(symbols,S_Day, S_Month, S_Year, E_Day, E_Month, E_Year):
    yf.pdr_override()        
    stocks_yahoo = pdr.get_data_yahoo(symbols, start=datetime(S_Year, S_Month, S_Day), end=datetime(E_Year, E_Month, E_Day),   as_panel = False,)
    return stocks_yahoo

# Índices da Carteira IMOB
Stocks=['ALSC3','BRML3', 'BRPR3','CYRE3','DIRR3','EVEN3','EZTC3','GFSA3','HBOR3','IGTA3','MRVE3','MULT3','TEND3']
Stocks=[Stocks[k]+'.SA' for k in range(len(Stocks))]

N_months=24
today = dt.date.today()
E_Day = today.day; E_Month = today.month; E_Year = today.year
day_before=today - dt.timedelta(days=N_months*365/12)
S_Day = day_before.day; S_Month = day_before.month; S_Year = day_before.year

stocks_all=yahoo(Stocks,S_Day, S_Month, S_Year, E_Day, E_Month, E_Year)
stocks_all

[*********************100%***********************]  13 of 13 downloaded

                 Open                                                          \
             ALSC3.SA BRML3.SA BRPR3.SA CYRE3.SA DIRR3.SA EVEN3.SA   EZTC3.SA
Date
2016-09-26  15.670000  10.6957     8.37     9.94     5.94     3.97  15.640000
2016-09-27  15.530000  10.7130     8.35     9.89     5.80     3.98  15.200000
2016-09-28  15.690000  10.8087     8.29     9.83     5.78     3.98  15.240000
2016-09-29  15.850000  10.8696     8.15    10.09     5.90     3.93  15.630000
2016-09-30  15.490000  10.6783     8.36    10.20     5.99     3.89  15.600000
2016-10-03  15.610000  10.6435     8.54    10.35     5.77     3.85  15.340000
2016-10-04  15.700000  10.9130     8.55    10.55     5.98     3.96  15.380000
2016-10-05  15.810000  11.0435     8.53    10.35     5.80     3.95  15.360000
2016-10-06  15.990000  11.0435     8.58    10.51     5.71     3.94  15.450000
2016-10-07  16.070000  11.0783     8.49    10.64     5.65     3.98  15.570000
2016-10-10  16.020000  11.2696     8.58    10.74     5.78     4.02  15.330000
2016-10-11  15.750000  11.2609     8.59    10.84     5.67     4.01  15.440000
2016-10-13  15.840000  11.0522     8.55    10.86     5.68     3.96  15.730000
2016-10-14  15.820000  11.2435     8.61    10.77     5.56     4.03  15.500000
2016-10-17  16.120001  11.1478     8.51    10.82     5.49     4.05  15.680000
2016-10-18  16.600000  11.3913     8.55    10.65     5.50     4.16  15.720000
2016-10-19  16.850000  11.7391     8.53    10.77     5.52     4.31  16.049999
2016-10-20  16.709999  11.9478     8.65    10.77     5.68     4.25  16.389999
2016-10-21  16.980000  11.7826     8.56    10.70     5.45     4.25  16.379999
2016-10-24  16.860001  11.6696     8.59    10.67     5.55     4.37  16.490000
2016-10-25  17.010000  11.6783     8.63    11.11     5.57     4.33  16.600000
2016-10-26  16.870001  11.5565     8.53    10.87     5.56     4.35  16.340000
2016-10-27  16.680000  11.4870     8.71    10.88     5.67     4.51  16.600000
2016-10-28  16.889999  11.3043     8.60    10.83     5.71     4.32  16.900000
2016-10-31  16.370001  11.2783     8.58    10.84     5.61     4.39  16.600000
2016-11-01  16.750000  11.1565     8.54    10.76     5.50     4.44  16.549999
2016-11-03  16.260000  10.7304     8.60    10.63     5.40     4.30  16.000000
2016-11-04  15.920000  10.5913     8.45    10.36     5.11     4.21  15.930000
2016-11-07  15.860000  10.5304     8.63    10.35     5.25     4.23  16.030001
2016-11-08  16.160000  10.7739     8.77    10.79     5.43     4.51  16.400000
...               ...      ...      ...      ...      ...      ...        ...
2018-08-10  14.890000   9.8400     8.64    12.09     6.94     3.70  17.200001
2018-08-13  14.700000   9.5000     8.48    11.62     6.89     3.58  16.760000
2018-08-14  14.950000   9.6500     8.40    11.70     7.09     3.69  16.709999
2018-08-15  15.140000   9.6500     8.29    11.84     6.92     3.80  17.389999
2018-08-16  15.150000   9.7200     8.27    11.75     6.99     3.77  17.150000
2018-08-17  15.200000   9.5700     8.21    11.45     6.81     3.77  16.820000
2018-08-20  14.990000   9.4000     8.49    11.24     6.81     3.73  16.350000
2018-08-21  15.300000   9.3600     8.33    11.07     6.80     3.69  16.139999
2018-08-22  14.700000   9.1100     8.72    10.70     6.72     3.50  15.680000
2018-08-23  14.870000   9.3500     8.87    11.00     6.84     3.59  16.230000
2018-08-24  14.780000   9.1700     8.96    10.96     6.85     3.52  15.940000
2018-08-27  14.880000   9.1700     8.98    10.67     6.65     3.50  16.040001
2018-08-28  15.180000   9.3800     9.02    10.85     6.91     3.52  16.620001
2018-08-29  15.230000   9.4400     8.97    10.91     6.86     3.51  16.350000
2018-08-30  15.240000   9.3900     8.82    10.90     6.85     3.49  16.450001
2018-08-31  14.790000   9.1300     9.23    10.75     6.78     3.45  16.330000
2018-09-03  15.120000   9.0600     9.10    10.78     6.74     3.47  16.049999
2018-09-04  14.970000   9.1900     8.99    10.73     6.90     3.43  16.059999
2018-09-05  14.640000   9.0900     9.00    10.64     6.68     3.37  15.720000
2018-09-06  14.730000   9.1400     8.97    10.68     6.71     3.39  16.000000
2018-09-10  14.920000   9.3000     8.85    10.83     6.76     3.41  15.970000
2018-09-11  14.400000   9.2200     8.70    10.55     6.72     3.36  15.990000
2018-09-12  14.240000   9.1400     8.58    10.42     6.63     3.30  15.930000
2018-09-13  14.260000   9.3800     8.41    10.35     6.55     3.33  16.090000
2018-09-14  13.990000   9.3200     8.25    10.10     6.43     3.30  15.650000
2018-09-17  14.080000   9.3200     8.44    10.31     6.36     3.20  15.820000
2018-09-18  14.260000   9.6200     8.56    10.41     6.46     3.21  16.450001
2018-09-19  14.470000   9.7000     8.47    10.45     6.60     3.18  16.270000
2018-09-20  14.370000   9.7500     8.44    10.69     6.55     3.15  17.000000
2018-09-21  14.500000   9.7700     8.58    10.60     6.59     3.10  16.559999

                                             ...       Volume           \
             GFSA3.SA HBOR3.SA   IGTA3.SA    ...     CYRE3.SA DIRR3.SA
Date                                         ...
2016-09-26  19.326000  1.87037  28.600000    ...      2733200   545400
2016-09-27  20.399700  1.86078  29.000000    ...      2140600   501300
2016-09-28  20.161100  2.01425  29.500000    ...      3635500   522800
2016-09-29  19.803200  2.03343  29.830000    ...      1760800   571300
2016-09-30  19.922501  2.07180  29.730000    ...      1642600   501800
2016-10-03  19.922501  1.99506  29.700001    ...      2189100   311700
2016-10-04  20.399700  1.94711  30.090000    ...      1125400  1314700
2016-10-05  20.399700  1.87996  30.040001    ...      1844200   745600
2016-10-06  20.757500  1.84160  30.250000    ...      1064400   806900
2016-10-07  20.638300  1.88956  30.090000    ...      1836500   547200
2016-10-10  20.638300  1.86078  30.600000    ...      1135100   522800
2016-10-11  20.280399  1.86078  30.280001    ...      1388200   421000
2016-10-13  20.041800  1.85119  29.430000    ...      2259700   513600
2016-10-14  20.161100  1.85119  30.150000    ...      1484900   680200
2016-10-17  19.922501  1.95670  30.120001    ...      1899000   609300
2016-10-18  20.041800  1.92792  30.400000    ...      1847700   763100
2016-10-19  20.876900  1.89915  30.910000    ...      2236400   470200
2016-10-20  21.831200  1.93751  30.700001    ...      1974600  3779500
2016-10-21  23.262800  2.10057  30.879999    ...      3881200   902200
2016-10-24  23.024200  2.14853  30.900000    ...      3862800   423400
2016-10-25  23.501400  2.06221  30.879999    ...      3282200   389900
2016-10-26  21.473301  1.98547  29.980000    ...      2751600   480400
2016-10-27  21.115400  1.94711  30.120001    ...      1631400   291000
2016-10-28  20.399700  1.91833  29.700001    ...      2288100   229000
2016-10-31  19.922501  1.96629  29.740000    ...      5516300   518800
2016-11-01  19.683901  1.90874  30.090000    ...      2144600   546300
2016-11-03  19.445299  1.80323  28.959999    ...      3594700   880000
2016-11-04  18.848801  1.70731  28.620001    ...      2185800   736300
2016-11-07  19.803200  1.72650  28.809999    ...      3376400   551900
2016-11-08  20.757500  1.72650  29.309999    ...      2400300   430500
...               ...      ...        ...    ...          ...      ...
2018-08-10  12.020000  1.08000  31.680000    ...      4378400   594800
2018-08-13  12.100000  1.06000  30.719999    ...      1701200   832200
2018-08-14  12.190000  1.07000  31.760000    ...      2039900   843900
2018-08-15  12.240000  1.03000  31.290001    ...      1880200   509100
2018-08-16  12.120000  1.04000  30.680000    ...      1366700   584400
2018-08-17  12.100000  1.00000  30.540001    ...      1262600   504200
2018-08-20  12.150000  1.00000  30.370001    ...      1186900   499000
2018-08-21  12.230000  1.00000  31.080000    ...      2674900   609200
2018-08-22  12.200000  0.98000  30.639999    ...      2622200   565600
2018-08-23  12.170000  1.04000  31.080000    ...      1375900   601100
2018-08-24  12.160000  1.02000  30.799999    ...      1766500   806900
2018-08-27  11.970000  1.01000  30.950001    ...      1538700   628500
2018-08-28  11.610000  1.02000  31.219999    ...      1542300   390600
2018-08-29  11.570000  1.00000  31.389999    ...      1595900   381600
2018-08-30  11.170000  1.00000  31.299999    ...      1007900   380600
2018-08-31  11.440000  0.99000  30.980000    ...      1617500   681200
2018-09-03  11.180000  0.99000  30.590000    ...      1167500   183200
2018-09-04  11.130000  0.98000  30.450001    ...      2352300  1084200
2018-09-05  11.220000  0.95000  29.660000    ...      2038800   560000
2018-09-06  11.250000  0.96000  29.670000    ...      1584300   571300
2018-09-10  11.210000  0.97000  30.129999    ...      1903900   955100
2018-09-11  11.130000  0.97000  29.700001    ...      2763000   774900
2018-09-12  11.270000  0.96000  29.950001    ...      1626100   602700
2018-09-13  11.300000  0.97000  29.730000    ...      3146400   785100
2018-09-14  11.200000  0.95000  29.459999    ...      2289600   798100
2018-09-17  11.280000  1.03000  28.850000    ...      3225200  1142300
2018-09-18  11.180000  1.01000  29.620001    ...      2656800   565300
2018-09-19  11.260000  1.01000  29.700001    ...      3018000   490800
2018-09-20  11.130000  1.04000  29.889999    ...      2065300   402700
2018-09-21  11.110000  1.07000  29.660000    ...      6051300   881500

                                                                           \
           EVEN3.SA EZTC3.SA GFSA3.SA HBOR3.SA IGTA3.SA MRVE3.SA MULT3.SA
Date
2016-09-26   339600  1091000   893096   425683   258000  2278400   796500
2016-09-27   529600   443400   614194  1229715   303100  1278200  1740000
2016-09-28   664700   703400   315584   545891   285300  1189100  2536200
2016-09-29   555500   571900   358477  1203859   340200  1315600  2463600
2016-09-30   429200   622300   307327   337168   541200  2005500  2153700
2016-10-03   571500   420900   340430   507629   673400  1315500  1601400
2016-10-04   303400   404600   243218   954163   193800  1371500  2153100
2016-10-05   294700   901300   658210   749401   200500  2063900  1180500
2016-10-06   338300   710100   256898   566638   189500   981600  1527600
2016-10-07   484000   899600   263780   566430   574400  2821000  2486400
2016-10-10   319900   320200   224416   257099   337500  1662300  1045500
2016-10-11   329800   743600   199646   179114  2873000  2099600  1215600
2016-10-13   933300   745800   404120   270548  1196900  2811700  1480800
2016-10-14   822500   620800   599818  1499220   253300  1847800  1299300
2016-10-17   483500   505200   450869  1007230   484100  3393200   987300
2016-10-18  1049000   569600   391680   965840   658300  3044600  1766100
2016-10-19   611000   811700  1615608  1726292   674800  1220800  1872000
2016-10-20   570100   744400  1203608  1662487   525900  1389700  2012100
2016-10-21  1639700   814600  1536972  2036771   544200  2848700  1279500
2016-10-24   407800   873200  1090872  1173833   214100  1647600  1005000
2016-10-25   736700  1684000  1887058  1071140   652100  2414100  1220400
2016-10-26   778900   448100   916483   631903   604200  1611000  1756500
2016-10-27  1195300   837700   913717   639619  1443400  1595600  1550400
2016-10-28   296000   556800  2132648   374388   348100  1773000  2447100
2016-10-31   302500   536300  1606873   733242   630000  2027200  1837800
2016-11-01   410500   524000   659224  2223495   831900  2801000  2179800
2016-11-03   856500   397100   612601  1641635   725400  3485900  2308200
2016-11-04   281600   443800   624009  1156943   683000  1574600  2383200
2016-11-07  1932200   338000   925922   709992   836700  3048800  1113000
2016-11-08   717200   425000   539028   260956  1368800  1913100  1474200
...             ...      ...      ...      ...      ...      ...      ...
2018-08-10  1145600   764700  1544800   497400   754400  2441700  3301300
2018-08-13   806600   477700   554100   748400   732500  2105800  1680100
2018-08-14   743200   403300  1124800   196300   848200  2386500  1752300
2018-08-15   505700   422800   804100   604800  1178500  1484900  1736100
2018-08-16   422000   275600   210100   908600   637400  1422500  1040600
2018-08-17  1355200   691700   542600   858600  1068400  1133100   928500
2018-08-20   201500   581000  1056000   457900  1368500  2878800  1490300
2018-08-21  1297600   789800  1805000   539400   610000  2607000  1394900
2018-08-22   481300   662100  1154200   960200   938100  2675100  1084100
2018-08-23   456300   479500  1090800   546900   631700  2225300  1604300
2018-08-24   799600   465600  2537900   594800   912000  1636300  2952300
2018-08-27   235000   360600  1005400   145400   992700  2325000  1169400
2018-08-28   447700   236900  1669000   528800   713000  2371400  1621200
2018-08-29   590100   143000  1387700   549500   752000  2622500  1259800
2018-08-30   622300   254800  1447400   286800   989000  1129600  1733400
2018-08-31   321400   517800  1248200   559200  1123300  3944800  2084800
2018-09-03    92200   258500   589300  1748200   734500  1389200   913000
2018-09-04   436300   437000   696200   412500  2444800  3507100  2165200
2018-09-05   328300   163800   373500   610100   699600  1937500  1717100
2018-09-06   586000   430900   320400   568300  1096400  1650700  1773100
2018-09-10   213300   393600  1422800   298200   739200  3303700  1512100
2018-09-11   255200   563600  1291000   659700   487400  2498200  1453200
2018-09-12   321800   355000  1009200   397800   996600  2089100  2409400
2018-09-13   211000   588100  1075300   217100   665900  2015400  1757500
2018-09-14   582800   225800   964400   999800  1270800  3894100  1480300
2018-09-17   382900   283300  1404200   370400   901600  1574000  2069500
2018-09-18   298500   299800  2096900   417900  1020000  1959900  4152800
2018-09-19   747700   657400  1698900   995000  1038100  3066500  1761000
2018-09-20   514100   453500   126200   602900   965800  3228300  1467400
2018-09-21   765800   268300   245100  1452300   786600  7296100  3219000


             TEND3.SA
Date
2016-09-26        NaN
2016-09-27        NaN
2016-09-28        NaN
2016-09-29        NaN
2016-09-30        NaN
2016-10-03        NaN
2016-10-04        NaN
2016-10-05        NaN
2016-10-06        NaN
2016-10-07        NaN
2016-10-10        NaN
2016-10-11        NaN
2016-10-13        NaN
2016-10-14        NaN
2016-10-17        NaN
2016-10-18        NaN
2016-10-19        NaN
2016-10-20        NaN
2016-10-21        NaN
2016-10-24        NaN
2016-10-25        NaN
2016-10-26        NaN
2016-10-27        NaN
2016-10-28        NaN
2016-10-31        NaN
2016-11-01        NaN
2016-11-03        NaN
2016-11-04        NaN
2016-11-07        NaN
2016-11-08        NaN
...               ...
2018-08-10   373700.0
2018-08-13   321700.0
2018-08-14   595200.0
2018-08-15   502100.0
2018-08-16   700100.0
2018-08-17   324300.0
2018-08-20   542700.0
2018-08-21   592600.0
2018-08-22   886300.0
2018-08-23   507300.0
2018-08-24   628500.0
2018-08-27   789100.0
2018-08-28   419600.0
2018-08-29   253000.0
2018-08-30   780800.0
2018-08-31   585900.0
2018-09-03   205400.0
2018-09-04   394500.0
2018-09-05   601800.0
2018-09-06   471100.0
2018-09-10   443400.0
2018-09-11   726500.0
2018-09-12   506000.0
2018-09-13   548500.0
2018-09-14   782400.0
2018-09-17   421900.0
2018-09-18   634800.0
2018-09-19   857000.0
2018-09-20  1706600.0
2018-09-21   926600.0

[503 rows x 78 columns]

In [34]:
stocks_volume = stocks_all['Volume'] # Apenas os Volumes diários de cada índice.
stocks_volume

,ALSC3.SA,BRML3.SA,BRPR3.SA,CYRE3.SA,DIRR3.SA,EVEN3.SA,EZTC3.SA,GFSA3.SA,HBOR3.SA,IGTA3.SA,MRVE3.SA,MULT3.SA,TEND3.SA
Date,,,,,,,,,,,,,
2016-09-26,289800,2239395,322800,2733200,545400,339600,1091000,893096,425683,258000,2278400,796500,NaN
2016-09-27,637500,2896505,481000,2140600,501300,529600,443400,614194,1229715,303100,1278200,1740000,NaN
2016-09-28,383200,3364095,481100,3635500,522800,664700,703400,315584,545891,285300,1189100,2536200,NaN
2016-09-29,230600,3741985,1158800,1760800,571300,555500,571900,358477,1203859,340200,1315600,2463600,NaN
2016-09-30,419600,5047235,413500,1642600,501800,429200,622300,307327,337168,541200,2005500,2153700,NaN
2016-10-03,515800,7689935,559100,2189100,311700,571500,420900,340430,507629,673400,1315500,1601400,NaN
2016-10-04,344400,7061000,213900,1125400,1314700,303400,404600,243218,954163,193800,1371500,2153100,NaN
2016-10-05,310000,3243345,144400,1844200,745600,294700,901300,658210,749401,200500,2063900,1180500,NaN
2016-10-06,198900,4269375,292400,1064400,806900,338300,710100,256898,566638,189500,981600,1527600,NaN
2016-10-07,939200,10179685,191600,1836500,547200,484000,899600,263780,566430,574400,2821000,2486400,NaN
2016-10-10,463300,3587425,411300,1135100,522800,319900,320200,224416,257099,337500,1662300,1045500,NaN
2016-10-11,247400,5806810,390200,1388200,421000,329800,743600,199646,179114,2873000,2099600,1215600,NaN
2016-10-13,266200,7994685,438200,2259700,513600,933300,745800,404120,270548,1196900,2811700,1480800,NaN
2016-10-14,518700,6634810,328600,1484900,680200,822500,620800,599818,1499220,253300,1847800,1299300,NaN
2016-10-17,601400,11259650,393800,1899000,609300,483500,505200,450869,1007230,484100,3393200,987300,NaN
2016-10-18,986600,8348655,596500,1847700,763100,1049000,569600,391680,965840,658300,3044600,1766100,NaN
2016-10-19,983600,9005190,304700,2236400,470200,611000,811700,1615608,1726292,674800,1220800,1872000,NaN
2016-10-20,490200,8757135,217600,1974600,3779500,570100,744400,1203608,1662487,525900,1389700,2012100,NaN
2016-10-21,1116000,5877535,151200,3881200,902200,1639700,814600,1536972,2036771,544200,2848700,1279500,NaN
2016-10-24,350800,4777330,335500,3862800,423400,407800,873200,1090872,1173833,214100,1647600,1005000,NaN
2016-10-25,604100,4735355,189800,3282200,389900,736700,1684000,1887058,1071140,652100,2414100,1220400,NaN
2016-10-26,334200,4326300,415000,2751600,480400,778900,448100,916483,631903,604200,1611000,1756500,NaN
2016-10-27,658600,3707715,262300,1631400,291000,1195300,837700,913717,639619,1443400,1595600,1550400,NaN
2016-10-28,295600,7436820,248600,2288100,229000,296000,556800,2132648,374388,348100,1773000,2447100,NaN
2016-10-31,310700,4829540,305600,5516300,518800,302500,536300,1606873,733242,630000,2027200,1837800,NaN
2016-11-01,459300,5548980,433300,2144600,546300,410500,524000,659224,2223495,831900,2801000,2179800,NaN
2016-11-03,397300,8876620,253500,3594700,880000,856500,397100,612601,1641635,725400,3485900,2308200,NaN
2016-11-04,360200,9579730,241000,2185800,736300,281600,443800,624009,1156943,683000,1574600,2383200,NaN
2016-11-07,211300,9349730,400400,3376400,551900,1932200,338000,925922,709992,836700,3048800,1113000,NaN
2016-11-08,280500,6152155,1096500,2400300,430500,717200,425000,539028,260956,1368800,1913100,1474200,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-08-10,339500,6575700,687400,4378400,594800,1145600,764700,1544800,497400,754400,2441700,3301300,373700.0
2018-08-13,393000,4108400,345300,1701200,832200,806600,477700,554100,748400,732500,2105800,1680100,321700.0
2018-08-14,204100,3646100,640900,2039900,843900,743200,403300,1124800,196300,848200,2386500,1752300,595200.0
2018-08-15,437300,6080800,837900,1880200,509100,505700,422800,804100,604800,1178500,1484900,1736100,502100.0
2018-08-16,345200,4189300,390700,1366700,584400,422000,275600,210100,908600,637400,1422500,1040600,700100.0
2018-08-17,365400,3921100,338800,1262600,504200,1355200,691700,542600,858600,1068400,1133100,928500,324300.0
2018-08-20,761100,4152500,160400,1186900,499000,201500,581000,1056000,457900,1368500,2878800,1490300,542700.0
2018-08-21,557000,6553500,370600,2674900,609200,1297600,789800,1805000,539400,610000,2607000,1394900,592600.0
2018-08-22,127000,4122400,1097000,2622200,565600,481300,662100,1154200,960200,938100,2675100,1084100,886300.0
2018-08-23,751100,3698400,552600,1375900,601100,456300,479500,1090800,546900,631700,2225300,1604300,507300.0
2018-08-24,477500,6448500,129500,1766500,806900,799600,465600,2537900,594800,912000,1636300,2952300,628500.0
2018-08-27,722400,6282200,252000,1538700,628500,235000,360600,1005400,145400,992700,2325000,1169400,789100.0
2018-08-28,657900,2943200,313100,1542300,390600,447700,236900,1669000,528800,713000,2371400,1621200,419600.0
2018-08-29,720400,4002400,123900,1595900,381600,590100,143000,1387700,549500,752000,2622500,1259800,253000.0
2018-08-30,433000,5521400,176400,1007900,380600,622300,254800,1447400,286800,989000,1129600,1733400,780800.0
2018-08-31,531700,7720400,382600,1617500,681200,321400,517800,1248200,559200,1123300,3944800,2084800,585900.0
2018-09-03,174500,2510200,129100,1167500,183200,92200,258500,589300,1748200,734500,1389200,913000,205400.0
2018-09-04,655400,10294200,196900,2352300,1084200,436300,437000,696200,412500,2444800,3507100,2165200,394500.0
2018-09-05,353400,4208200,210600,2038800,560000,328300,163800,373500,610100,699600,1937500,1717100,601800.0
2018-09-06,387900,9400800,218600,1584300,571300,586000,430900,320400,568300,1096400,1650700,1773100,471100.0
2018-09-10,599300,4698200,218400,1903900,955100,213300,393600,1422800,298200,739200,3303700,1512100,443400.0
2018-09-11,584700,3362000,227700,2763000,774900,255200,563600,1291000,659700,487400,2498200,1453200,726500.0
2018-09-12,475800,5624100,359400,1626100,602700,321800,355000,1009200,397800,996600,2089100,2409400,506000.0
2018-09-13,500600,7606900,99100,3146400,785100,211000,588100,1075300,217100,665900,2015400,1757500,548500.0
2018-09-14,470200,6328400,1503100,2289600,798100,582800,225800,964400,999800,1270800,3894100,1480300,782400.0
2018-09-17,271100,4415600,151100,3225200,1142300,382900,283300,1404200,370400,901600,1574000,2069500,421900.0
2018-09-18,262900,5895400,175900,2656800,565300,298500,299800,2096900,417900,1020000,1959900,4152800,634800.0
2018-09-19,244600,7774400,143300,3018000,490800,747700,657400,1698900,995000,1038100,3066500,1761000,857000.0
2018-09-20,234200,2998800,105800,2065300,402700,514100,453500,126200,602900,965800,3228300,1467400,1706600.0
2018-09-21,427400,5793500,318000,6051300,881500,765800,268300,245100,1452300,786600,7296100,3219000,926600.0

In [39]:
media_volume = stocks_volume.fillna(0).mean()
mediaVolume = pd.DataFrame.from_dict(media_volume)
mediaVolume.columns=["Média"]
mediaVolume.sort_values('Média',ascending=False) #Organizados a partir dos que possuem média mais alta

                 Média
BRML3.SA  5.732089e+06
MRVE3.SA  2.899011e+06
MULT3.SA  2.272967e+06
CYRE3.SA  2.270075e+06
HBOR3.SA  1.508014e+06
IGTA3.SA  1.039030e+06
EVEN3.SA  8.341724e+05
GFSA3.SA  7.854565e+05
DIRR3.SA  7.546577e+05
BRPR3.SA  6.746660e+05
EZTC3.SA  5.502010e+05
ALSC3.SA  5.484221e+05
TEND3.SA  3.742014e+05

In [43]:

MaisLiquidos = mediaVolume.sort_values('Média',ascending=False).iloc[:5]
MaisLiquidos #5 índices mais líquidos dos 13 selecionados inicialmente

                 Média
BRML3.SA  5.732089e+06
MRVE3.SA  2.899011e+06
MULT3.SA  2.272967e+06
CYRE3.SA  2.270075e+06
HBOR3.SA  1.508014e+06

In [63]:
Liquidos=['BRML3', 'CYRE3','HBOR3','MRVE3','MULT3']
Liquidos=[Liquidos[k]+'.SA' for k in range(len(Liquidos))]

N_months=24
today = dt.date.today()
E_Day = today.day; E_Month = today.month; E_Year = today.year
day_before=today - dt.timedelta(days=N_months*365/12)
S_Day = day_before.day; S_Month = day_before.month; S_Year = day_before.year

liquidos_all=yahoo(Liquidos,S_Day, S_Month, S_Year, E_Day, E_Month, E_Year)
liquidos_all

[*********************100%***********************]  5 of 5 downloaded

               Open                                           High           \
           BRML3.SA CYRE3.SA HBOR3.SA MRVE3.SA   MULT3.SA BRML3.SA CYRE3.SA
Date
2016-09-26  10.6957     9.94  1.87037    11.67  20.400000  10.8870    10.11
2016-09-27  10.7130     9.89  1.86078    11.60  20.763300  10.8696     9.95
2016-09-28  10.8087     9.83  2.01425    11.77  21.120001  10.9130    10.24
2016-09-29  10.8696    10.09  2.03343    11.92  21.379999  10.9044    10.34
2016-09-30  10.6783    10.20  2.07180    12.08  21.346701  10.7913    10.26
2016-10-03  10.6435    10.35  1.99506    12.04  21.066700  11.1304    10.55
2016-10-04  10.9130    10.55  1.94711    11.95  21.446699  11.0522    10.56
2016-10-05  11.0435    10.35  1.87996    11.92  21.440001  11.1652    10.58
2016-10-06  11.0435    10.51  1.84160    12.09  21.389999  11.0435    10.67
2016-10-07  11.0783    10.64  1.88956    12.14  21.440001  11.3217    10.77
2016-10-10  11.2696    10.74  1.86078    12.24  21.623301  11.3913    10.85
2016-10-11  11.2609    10.84  1.86078    12.14  21.693300  11.3217    10.89
2016-10-13  11.0522    10.86  1.85119    12.28  21.113300  11.2261    10.86
2016-10-14  11.2435    10.77  1.85119    12.14  21.129999  11.3217    10.90
2016-10-17  11.1478    10.82  1.95670    12.06  21.223301  11.3826    10.85
2016-10-18  11.3913    10.65  1.92792    12.29  21.346701  11.8348    10.86
2016-10-19  11.7391    10.77  1.89915    12.70  21.913300  11.9130    11.00
2016-10-20  11.9478    10.77  1.93751    12.63  21.670000  11.9565    10.82
2016-10-21  11.7826    10.70  2.10057    12.56  21.643299  11.8435    10.81
2016-10-24  11.6696    10.67  2.14853    12.49  21.533300  11.8783    11.12
2016-10-25  11.6783    11.11  2.06221    12.79  21.413300  11.7565    11.14
2016-10-26  11.5565    10.87  1.98547    12.54  20.870001  11.6000    11.03
2016-10-27  11.4870    10.88  1.94711    12.58  20.850000  11.6522    11.00
2016-10-28  11.3043    10.83  1.91833    12.64  20.893299  11.3217    11.05
2016-10-31  11.2783    10.84  1.96629    12.56  20.920000  11.2783    10.94
2016-11-01  11.1565    10.76  1.90874    12.41  21.386700  11.1652    10.82
2016-11-03  10.7304    10.63  1.80323    12.03  20.400000  10.8174    10.70
2016-11-04  10.5913    10.36  1.70731    11.88  20.263300  10.7304    10.42
2016-11-07  10.5304    10.35  1.72650    12.00  20.603300  11.0087    10.80
2016-11-08  10.7739    10.79  1.72650    12.12  20.650000  10.8783    11.03
...             ...      ...      ...      ...        ...      ...      ...
2018-08-10   9.8400    12.09  1.08000    13.72  18.980000   9.8400    12.09
2018-08-13   9.5000    11.62  1.06000    13.17  18.510000   9.6500    11.92
2018-08-14   9.6500    11.70  1.07000    13.70  19.030001   9.9200    12.12
2018-08-15   9.6500    11.84  1.03000    13.61  18.959999   9.7700    11.87
2018-08-16   9.7200    11.75  1.04000    13.58  18.870001   9.9200    11.96
2018-08-17   9.5700    11.45  1.00000    13.26  18.700001   9.6500    11.54
2018-08-20   9.4000    11.24  1.00000    13.00  18.459999   9.5800    11.35
2018-08-21   9.3600    11.07  1.00000    13.00  18.680000   9.4000    11.22
2018-08-22   9.1100    10.70  0.98000    12.96  18.260000   9.3600    11.09
2018-08-23   9.3500    11.00  1.04000    13.02  18.650000   9.4100    11.23
2018-08-24   9.1700    10.96  1.02000    13.06  18.639999   9.3400    11.02
2018-08-27   9.1700    10.67  1.01000    12.90  18.690001   9.5500    11.00
2018-08-28   9.3800    10.85  1.02000    13.16  18.910000   9.4500    10.96
2018-08-29   9.4400    10.91  1.00000    13.10  18.900000   9.5500    11.20
2018-08-30   9.3900    10.90  1.00000    13.10  18.910000   9.4700    10.93
2018-08-31   9.1300    10.75  0.99000    12.82  18.809999   9.3300    11.05
2018-09-03   9.0600    10.78  0.99000    12.91  18.450001   9.1800    10.86
2018-09-04   9.1900    10.73  0.98000    13.02  18.559999   9.2300    10.73
2018-09-05   9.0900    10.64  0.95000    12.63  18.350000   9.1100    10.71
2018-09-06   9.1400    10.68  0.96000    12.55  18.700001   9.3300    10.75
2018-09-10   9.3000    10.83  0.97000    12.84  18.750000   9.4500    11.02
2018-09-11   9.2200    10.55  0.97000    12.39  18.200001   9.2700    10.56
2018-09-12   9.1400    10.42  0.96000    12.34  18.340000   9.5000    10.44
2018-09-13   9.3800    10.35  0.97000    12.48  18.150000   9.5300    10.39
2018-09-14   9.3200    10.10  0.95000    12.08  17.920000   9.4900    10.43
2018-09-17   9.3200    10.31  1.03000    12.20  17.969999   9.6900    10.52
2018-09-18   9.6200    10.41  1.01000    12.23  18.420000   9.9000    10.80
2018-09-19   9.7000    10.45  1.01000    12.20  18.600000   9.8600    10.89
2018-09-20   9.7500    10.69  1.04000    12.68  18.580000   9.7800    10.81
2018-09-21   9.7700    10.60  1.07000    12.23  18.480000  10.0400    10.72

                                          ...     Adj Close             \
           HBOR3.SA MRVE3.SA   MULT3.SA   ...      BRML3.SA   CYRE3.SA
Date                                      ...
2016-09-26  1.88956    11.67  20.826700   ...     10.680888   9.372112
2016-09-27  1.98547    11.83  21.183300   ...     10.680888   9.372112
2016-09-28  2.02384    12.03  21.686701   ...     10.732804   9.706149
2016-09-29  2.12935    12.23  21.566700   ...     10.568500   9.658429
2016-09-30  2.08139    12.12  21.490000   ...     10.637722   9.763412
2016-10-03  1.99506    12.04  21.770000   ...     10.897109   9.982923
2016-10-04  1.95670    12.13  21.696699   ...     10.931720   9.906571
2016-10-05  1.88956    12.22  21.740000   ...     11.035455  10.030643
2016-10-06  1.89915    12.11  21.520000   ...     10.966331  10.106993
2016-10-07  1.88956    12.30  21.770000   ...     11.199859  10.202432
2016-10-10  1.87037    12.38  21.870001   ...     11.182553  10.355135
2016-10-11  1.87996    12.35  21.693300   ...     11.052760  10.355135
2016-10-13  1.88956    12.28  21.299999   ...     11.147942  10.259695
2016-10-14  1.95670    12.26  21.593300   ...     11.087373  10.316959
2016-10-17  2.00466    12.27  21.473301   ...     11.320899  10.126081
2016-10-18  1.94711    12.72  22.083300   ...     11.736037  10.336046
2016-10-19  1.98547    12.74  22.209999   ...     11.822565  10.307415
2016-10-20  2.08139    12.63  21.879999   ...     11.718731  10.259695
2016-10-21  2.17731    12.60  21.750000   ...     11.666814  10.183345
2016-10-24  2.16771    12.82  21.683300   ...     11.692773  10.555556
2016-10-25  2.07180    12.80  21.526699   ...     11.502509  10.469662
2016-10-26  1.98547    12.70  21.213301   ...     11.416080  10.355135
2016-10-27  1.99506    12.81  21.426701   ...     11.199859  10.421942
2016-10-28  1.96629    12.79  21.103300   ...     11.096025  10.421942
2016-10-31  1.97588    12.56  21.496700   ...     11.052760  10.259695
2016-11-01  1.91833    12.53  21.483299   ...     10.724152  10.154713
2016-11-03  1.80323    12.33  20.646700   ...     10.456013   9.830220
2016-11-04  1.72650    12.07  21.056700   ...     10.378237   9.858851
2016-11-07  1.76486    12.34  21.106701   ...     10.776069  10.307415
2016-11-08  1.72650    12.62  21.000000   ...     10.551194  10.431486
...             ...      ...        ...   ...           ...        ...
2018-08-10  1.08000    13.87  19.330000   ...      9.510000  11.630000
2018-08-13  1.09000    13.58  19.030001   ...      9.560000  11.530000
2018-08-14  1.08000    13.89  19.540001   ...      9.800000  11.910000
2018-08-15  1.06000    13.67  19.129999   ...      9.730000  11.730000
2018-08-16  1.04000    13.70  19.170000   ...      9.680000  11.540000
2018-08-17  1.00000    13.32  18.950001   ...      9.430000  11.350000
2018-08-20  1.01000    13.27  18.969999   ...      9.410000  11.150000
2018-08-21  1.02000    13.22  18.850000   ...      9.160000  10.820000
2018-08-22  1.06000    13.21  18.850000   ...      9.360000  11.000000
2018-08-23  1.06000    13.33  19.040001   ...      9.080000  10.780000
2018-08-24  1.03000    13.11  18.790001   ...      9.180000  10.700000
2018-08-27  1.02000    13.17  19.160000   ...      9.450000  10.900000
2018-08-28  1.03000    13.29  19.030001   ...      9.430000  10.870000
2018-08-29  1.01000    13.28  19.209999   ...      9.480000  10.900000
2018-08-30  1.00000    13.20  19.160000   ...      9.200000  10.820000
2018-08-31  1.01000    13.17  19.090000   ...      9.150000  10.930000
2018-09-03  1.01000    13.06  18.629999   ...      9.120000  10.700000
2018-09-04  0.99000    13.08  18.930000   ...      9.000000  10.640000
2018-09-05  0.96000    12.66  18.629999   ...      9.010000  10.550000
2018-09-06  0.98000    12.82  18.730000   ...      9.300000  10.700000
2018-09-10  0.99000    13.03  18.830000   ...      9.440000  10.720000
2018-09-11  0.98000    12.45  18.370001   ...      9.050000  10.320000
2018-09-12  0.97000    12.61  18.559999   ...      9.390000  10.320000
2018-09-13  0.97000    12.52  18.240000   ...      9.360000  10.100000
2018-09-14  1.02000    12.31  18.090000   ...      9.320000  10.310000
2018-09-17  1.04000    12.34  18.450001   ...      9.610000  10.450000
2018-09-18  1.03000    12.39  18.620001   ...      9.830000  10.570000
2018-09-19  1.07000    12.78  18.650000   ...      9.650000  10.570000
2018-09-20  1.08000    12.70  18.770000   ...      9.660000  10.580000
2018-09-21  1.08000    12.41  19.100000   ...      9.880000  10.620000

                                             Volume                    \
           HBOR3.SA   MRVE3.SA   MULT3.SA  BRML3.SA CYRE3.SA HBOR3.SA
Date
2016-09-26  1.81282  10.776438  19.045738   2239395  2733200   425683
2016-09-27  1.98547  10.944237  19.450901   2896505  2140600  1229715
2016-09-28  2.01425  11.205258  19.687277   3364095  3635500   545891
2016-09-29  2.05261  11.177291  19.552193   3741985  1760800  1203859
2016-09-30  1.96629  11.130679  19.398783   5047235  1642600   337168
2016-10-03  1.94711  11.140002  19.843819   7689935  2189100   507629
2016-10-04  1.87996  11.074748  19.776321   7061000  1125400   954163
2016-10-05  1.83201  11.261191  19.825401   3243345  1844200   749401
2016-10-06  1.87996  11.251868  19.644274   4269375  1064400   566638
2016-10-07  1.84160  11.354414  19.960485  10179685  1836500   566430
2016-10-10  1.85119  11.354414  19.975771   3587425  1135100   257099
2016-10-11  1.85119  11.428990  19.539942   5806810  1388200   179114
2016-10-13  1.85119  11.167969  19.490866   7994685  2259700   270548
2016-10-14  1.91833  11.214581  19.625858   6634810  1484900  1499220
2016-10-17  1.90874  11.438313  19.671900  11259650  1899000  1007230
2016-10-18  1.88956  11.745944  20.248981   8348655  1847700   965840
2016-10-19  1.93751  11.755266  20.055609   9005190  2236400  1726292
2016-10-20  2.08139  11.671368  19.929729   8757135  1974600  1662487
2016-10-21  2.11976  11.634077  19.831570   5877535  3881200  2036771
2016-10-24  2.04302  11.867132  19.782398   4777330  3862800  1173833
2016-10-25  1.97588  11.699333  19.233034   4735355  3282200  1071140
2016-10-26  1.93751  11.792554  19.266735   4326300  2751600   631903
2016-10-27  1.91833  11.885777  19.398783   3707715  1631400   639619
2016-10-28  1.95670  11.680689  19.214615   7436820  2288100   374388
2016-10-31  1.94711  11.522212  19.690317   4829540  5516300   733242
2016-11-01  1.80323  11.382380  19.018112   5548980  2144600  2223495
2016-11-03  1.70731  11.046782  18.787905   8876620  3594700  1641635
2016-11-04  1.68813  11.046782  18.956785   9579730  2185800  1156943
2016-11-07  1.71691  11.447634  19.233034   9349730  3376400   709992
2016-11-08  1.69772  11.690011  19.260658   6152155  2400300   260956
...             ...        ...        ...       ...      ...      ...
2018-08-10  1.06000  13.340000  18.540001   6575700  4378400   497400
2018-08-13  1.07000  13.480000  18.840000   4108400  1701200   748400
2018-08-14  1.07000  13.800000  19.250000   3646100  2039900   196300
2018-08-15  1.03000  13.600000  18.920000   6080800  1880200   604800
2018-08-16  1.00000  13.400000  18.959999   4189300  1366700   908600
2018-08-17  1.00000  13.140000  18.660000   3921100  1262600   858600
2018-08-20  1.00000  13.130000  18.780001   4152500  1186900   457900
2018-08-21  0.99000  13.050000  18.309999   6553500  2674900   539400
2018-08-22  1.04000  13.150000  18.709999   4122400  2622200   960200
2018-08-23  1.02000  12.950000  18.309999   3698400  1375900   546900
2018-08-24  1.01000  12.870000  18.490000   6448500  1766500   594800
2018-08-27  1.02000  13.140000  19.110001   6282200  1538700   145400
2018-08-28  1.00000  13.100000  18.930000   2943200  1542300   528800
2018-08-29  1.00000  13.200000  19.150000   4002400  1595900   549500
2018-08-30  0.98000  12.840000  18.930000   5521400  1007900   286800
2018-08-31  0.99000  13.000000  18.629999   7720400  1617500   559200
2018-09-03  0.98000  13.000000  18.559999   2510200  1167500  1748200
2018-09-04  0.95000  12.650000  18.430000  10294200  2352300   412500
2018-09-05  0.95000  12.500000  18.600000   4208200  2038800   610100
2018-09-06  0.98000  12.730000  18.559999   9400800  1584300   568300
2018-09-10  0.97000  12.600000  18.500000   4698200  1903900   298200
2018-09-11  0.96000  12.220000  18.190001   3362000  2763000   659700
2018-09-12  0.95000  12.480000  18.090000   5624100  1626100   397800
2018-09-13  0.94000  12.140000  17.959999   7606900  3146400   217100
2018-09-14  1.02000  12.150000  17.930000   6328400  2289600   999800
2018-09-17  1.01000  12.180000  18.450001   4415600  3225200   370400
2018-09-18  1.01000  12.380000  18.580000   5895400  2656800   417900
2018-09-19  1.05000  12.650000  18.540001   7774400  3018000   995000
2018-09-20  1.07000  12.130000  18.480000   2998800  2065300   602900
2018-09-21  1.06000  12.290000  18.910000   5793500  6051300  1452300


           MRVE3.SA MULT3.SA
Date
2016-09-26  2278400   796500
2016-09-27  1278200  1740000
2016-09-28  1189100  2536200
2016-09-29  1315600  2463600
2016-09-30  2005500  2153700
2016-10-03  1315500  1601400
2016-10-04  1371500  2153100
2016-10-05  2063900  1180500
2016-10-06   981600  1527600
2016-10-07  2821000  2486400
2016-10-10  1662300  1045500
2016-10-11  2099600  1215600
2016-10-13  2811700  1480800
2016-10-14  1847800  1299300
2016-10-17  3393200   987300
2016-10-18  3044600  1766100
2016-10-19  1220800  1872000
2016-10-20  1389700  2012100
2016-10-21  2848700  1279500
2016-10-24  1647600  1005000
2016-10-25  2414100  1220400
2016-10-26  1611000  1756500
2016-10-27  1595600  1550400
2016-10-28  1773000  2447100
2016-10-31  2027200  1837800
2016-11-01  2801000  2179800
2016-11-03  3485900  2308200
2016-11-04  1574600  2383200
2016-11-07  3048800  1113000
2016-11-08  1913100  1474200
...             ...      ...
2018-08-10  2441700  3301300
2018-08-13  2105800  1680100
2018-08-14  2386500  1752300
2018-08-15  1484900  1736100
2018-08-16  1422500  1040600
2018-08-17  1133100   928500
2018-08-20  2878800  1490300
2018-08-21  2607000  1394900
2018-08-22  2675100  1084100
2018-08-23  2225300  1604300
2018-08-24  1636300  2952300
2018-08-27  2325000  1169400
2018-08-28  2371400  1621200
2018-08-29  2622500  1259800
2018-08-30  1129600  1733400
2018-08-31  3944800  2084800
2018-09-03  1389200   913000
2018-09-04  3507100  2165200
2018-09-05  1937500  1717100
2018-09-06  1650700  1773100
2018-09-10  3303700  1512100
2018-09-11  2498200  1453200
2018-09-12  2089100  2409400
2018-09-13  2015400  1757500
2018-09-14  3894100  1480300
2018-09-17  1574000  2069500
2018-09-18  1959900  4152800
2018-09-19  3066500  1761000
2018-09-20  3228300  1467400
2018-09-21  7296100  3219000

[503 rows x 30 columns]

In [64]:
close = liquidos_all['Close'].fillna(0)
Close = pd.DataFrame.from_dict(close)

Close

            BRML3.SA  CYRE3.SA  HBOR3.SA  MRVE3.SA   MULT3.SA
Date
2016-09-26   10.7391      9.82   1.81282     11.56  20.683300
2016-09-27   10.7391      9.82   1.98547     11.74  21.123301
2016-09-28   10.7913     10.17   2.01425     12.02  21.379999
2016-09-29   10.6261     10.12   2.05261     11.99  21.233299
2016-09-30   10.6957     10.23   1.96629     11.94  21.066700
2016-10-03   10.9565     10.46   1.94711     11.95  21.549999
2016-10-04   10.9913     10.38   1.87996     11.88  21.476700
2016-10-05   11.0956     10.51   1.83201     12.08  21.530001
2016-10-06   11.0261     10.59   1.87996     12.07  21.333300
2016-10-07   11.2609     10.69   1.84160     12.18  21.676701
2016-10-10   11.2435     10.85   1.85119     12.18  21.693300
2016-10-11   11.1130     10.85   1.85119     12.26  21.219999
2016-10-13   11.2087     10.75   1.85119     11.98  21.166700
2016-10-14   11.1478     10.81   1.91833     12.03  21.313299
2016-10-17   11.3826     10.61   1.90874     12.27  21.363300
2016-10-18   11.8000     10.83   1.88956     12.60  21.990000
2016-10-19   11.8870     10.80   1.93751     12.61  21.780001
2016-10-20   11.7826     10.75   2.08139     12.52  21.643299
2016-10-21   11.7304     10.67   2.11976     12.48  21.536699
2016-10-24   11.7565     11.06   2.04302     12.73  21.483299
2016-10-25   11.5652     10.97   1.97588     12.55  20.886700
2016-10-26   11.4783     10.85   1.93751     12.65  20.923300
2016-10-27   11.2609     10.92   1.91833     12.75  21.066700
2016-10-28   11.1565     10.92   1.95670     12.53  20.866699
2016-10-31   11.1130     10.75   1.94711     12.36  21.383301
2016-11-01   10.7826     10.64   1.80323     12.21  20.653299
2016-11-03   10.5130     10.30   1.70731     11.85  20.403299
2016-11-04   10.4348     10.33   1.68813     11.85  20.586700
2016-11-07   10.8348     10.80   1.71691     12.28  20.886700
2016-11-08   10.6087     10.93   1.69772     12.54  20.916700
...              ...       ...       ...       ...        ...
2018-08-10    9.5100     11.63   1.06000     13.34  18.540001
2018-08-13    9.5600     11.53   1.07000     13.48  18.840000
2018-08-14    9.8000     11.91   1.07000     13.80  19.250000
2018-08-15    9.7300     11.73   1.03000     13.60  18.920000
2018-08-16    9.6800     11.54   1.00000     13.40  18.959999
2018-08-17    9.4300     11.35   1.00000     13.14  18.660000
2018-08-20    9.4100     11.15   1.00000     13.13  18.780001
2018-08-21    9.1600     10.82   0.99000     13.05  18.309999
2018-08-22    9.3600     11.00   1.04000     13.15  18.709999
2018-08-23    9.0800     10.78   1.02000     12.95  18.309999
2018-08-24    9.1800     10.70   1.01000     12.87  18.490000
2018-08-27    9.4500     10.90   1.02000     13.14  19.110001
2018-08-28    9.4300     10.87   1.00000     13.10  18.930000
2018-08-29    9.4800     10.90   1.00000     13.20  19.150000
2018-08-30    9.2000     10.82   0.98000     12.84  18.930000
2018-08-31    9.1500     10.93   0.99000     13.00  18.629999
2018-09-03    9.1200     10.70   0.98000     13.00  18.559999
2018-09-04    9.0000     10.64   0.95000     12.65  18.430000
2018-09-05    9.0100     10.55   0.95000     12.50  18.600000
2018-09-06    9.3000     10.70   0.98000     12.73  18.559999
2018-09-10    9.4400     10.72   0.97000     12.60  18.500000
2018-09-11    9.0500     10.32   0.96000     12.22  18.190001
2018-09-12    9.3900     10.32   0.95000     12.48  18.090000
2018-09-13    9.3600     10.10   0.94000     12.14  17.959999
2018-09-14    9.3200     10.31   1.02000     12.15  17.930000
2018-09-17    9.6100     10.45   1.01000     12.18  18.450001
2018-09-18    9.8300     10.57   1.01000     12.38  18.580000
2018-09-19    9.6500     10.57   1.05000     12.65  18.540001
2018-09-20    9.6600     10.58   1.07000     12.13  18.480000
2018-09-21    9.8800     10.62   1.06000     12.29  18.910000

[503 rows x 5 columns]

In [75]:
retorno = 100*(np.log(Close.iloc[1][1:])-np.log(Close.iloc[1][:-1]))
#fig = plt.subplots(figsize=(7, 4))
retorno
#plt.stem(retorno)
#plt.ylabel('Retorno [%]')
#plt.xlabel('tempo [ms]')
#plt.title('Retorno Modelado com movimento browniano Geometrico')

BRML3.SA    NaN
CYRE3.SA    0.0
HBOR3.SA    0.0
MRVE3.SA    0.0
MULT3.SA    NaN
Name: 2016-09-27 00:00:00, dtype: float64

In [105]:
Close.index

DatetimeIndex(['2016-09-26', '2016-09-27', '2016-09-28', '2016-09-29',
               '2016-09-30', '2016-10-03', '2016-10-04', '2016-10-05',
               '2016-10-06', '2016-10-07',
               ...
               '2018-09-10', '2018-09-11', '2018-09-12', '2018-09-13',
               '2018-09-14', '2018-09-17', '2018-09-18', '2018-09-19',
               '2018-09-20', '2018-09-21'],
              dtype='datetime64[ns]', name='Date', length=503, freq=None)

In [110]:
retorno_BRML3 = Close['BRML3.SA'][1:].values/Close['BRML3.SA'][0:-1].values-1
retorno_CYRE3 = Close['CYRE3.SA'][1:].values/Close['CYRE3.SA'][0:-1].values-1
retorno_HBOR3 = Close['HBOR3.SA'][1:].values/Close['HBOR3.SA'][0:-1].values-1
retorno_MRVE3 = Close['MRVE3.SA'][1:].values/Close['MRVE3.SA'][0:-1].values-1
retorno_MULT3 = Close['MULT3.SA'][1:].values/Close['MULT3.SA'][0:-1].values-1
Retorno = {'R_BRML3': retorno_BRML3,
           'R_CYRE3': retorno_CYRE3,
           'R_HBOR3': retorno_HBOR3,
           'R_MRVE3': retorno_MRVE3,
           'R_MULT3': retorno_MULT3}
dfRetorno = pd.DataFrame(Retorno,index = Close.index[0:-1],columns =['R_BRML3','R_CYRE3','R_HBOR3','R_MRVE3','R_MULT3'])
dfRetorno.corr()

          R_BRML3   R_CYRE3   R_HBOR3   R_MRVE3   R_MULT3
R_BRML3  1.000000  0.579215  0.408622  0.455720  0.683837
R_CYRE3  0.579215  1.000000  0.470113  0.577268  0.597712
R_HBOR3  0.408622  0.470113  1.000000  0.420715  0.412820
R_MRVE3  0.455720  0.577268  0.420715  1.000000  0.489247
R_MULT3  0.683837  0.597712  0.412820  0.489247  1.000000

In [109]:
Close.corr()

          BRML3.SA  CYRE3.SA  HBOR3.SA  MRVE3.SA  MULT3.SA
BRML3.SA  1.000000  0.614562  0.842379  0.506172  0.919213
CYRE3.SA  0.614562  1.000000  0.396179  0.860675  0.681583
HBOR3.SA  0.842379  0.396179  1.000000  0.341437  0.697251
MRVE3.SA  0.506172  0.860675  0.341437  1.000000  0.591541
MULT3.SA  0.919213  0.681583  0.697251  0.591541  1.000000